version: 2

jobs:
  # Core
  python-3.7-core:
    docker:
      - image: circleci/python:3.7-stretch-node-browsers
        environment:
          PLOTLY_TOX_PYTHON_37: python3.7

    steps:
      - checkout
      - run:
          name: Install tox
          command: 'sudo pip install tox'
      - run:
          name: Test with tox
          command: 'tox -e py37-core'
          no_output_timeout: 20m

  # Optional
  python-3.7-optional:
    docker:
      - image: circleci/python:3.7-stretch-node-browsers
        environment:
          PLOTLY_TOX_PYTHON_37: python3.7

    steps:
      - checkout
      - run:
          name: Install tox
          command: 'sudo pip install tox'
      - run:
          name: Install npm dependencies
          command: cd plotly/tests/test_optional/test_jupyter && npm install
          no_output_timeout: 20m
      - run:
          name: Test with tox
          command: 'tox -e py37-optional'
          no_output_timeout: 20m

  # Plot.ly
  python-3.7-plot_ly:
    docker:
      - image: circleci/python:3.7-stretch-node-browsers
        environment:
          PLOTLY_TOX_PYTHON_37: python3.7

    steps:
      - checkout
      - run:
          name: Install tox
          command: 'sudo pip install tox'
      - run:
          name: Test with tox
          command: 'tox -e py37-plot_ly'
          no_output_timeout: 20m

  python-3-7-orca:
    docker:
      - image: circleci/node:10.9-stretch-browsers
        environment:
          PYTHON_VERSION: 3.7

    steps:
      - checkout
      - restore_cache:
          keys:
            - conda-37-v1-{{ checksum ".circleci/create_conda_optional_env.sh" }}
      - run:
          name: Create conda environment
          command: .circleci/create_conda_optional_env.sh

      - save_cache:
          key: conda-37-v1-{{ checksum ".circleci/create_conda_optional_env.sh" }}
          paths:
            - /home/circleci/miniconda/
      - run:
          name: Run Tests
          command: |
            . /home/circleci/miniconda/etc/profile.d/conda.sh
            conda activate circle_optional
            pytest --disable-warnings plotly/tests/test_core
            pytest plotly/tests/test_orca

      - store_artifacts:
            path: plotly/tests/test_orca/images/linux/failed

  python-3-7-conda:
    docker:
      - image: continuumio/miniconda3:4.5.4
        environment:
          PYTHON_VERSION: 3.7

    steps:
      - checkout
      - run:
          name: Create packages
          command: .circleci/create_conda_packages.sh
          no_output_timeout: 20m
      - store_artifacts:
          path: artifacts


workflows:
  version: 2
  build:
    jobs:
      - python-3.7-core
      # 3.7 optional disabled due to current shapely incompatibility
      # - python-3.7-optional
      - python-3.7-plot_ly
      - python-3-7-orca
      - python-3-7-conda:
          requires:
            - python-3.7-core
#            - python-3.7-optional
            - python-3.7-plot_ly
            - python-3-7-orca

          filters:
            branches:
              only:
                - master
                - /release_.*/
                - /conda_build_.*/
