version: 2

jobs:
  # Core
  python-3.7-core:
    docker:
      - image: circleci/python:3.7-stretch-node-browsers
        environment:
          PLOTLY_TOX_PYTHON_37: python3.7

    steps:
      - checkout
      - run:
          name: Install tox
          command: 'sudo pip install tox'
      - run:
          name: Test with tox
          command: 'tox -e py37-core'
          no_output_timeout: 20m


workflows:
  version: 2
  build:
    jobs:
      - python-3.7-core
